In [2]:
import numpy as np
import pandas as pd  
from sklearn.impute import SimpleImputer

In [19]:
df = pd.read_csv("googleplaystore.csv")

In [20]:
impute = SimpleImputer(missing_values=np.nan,strategy='mean')
impute.fit(df.iloc[ : , 2 : 3].values)
df.iloc[: , 2 : 3] = impute.transform(df.iloc[: , 2:3].values)
df = df.dropna()

In [5]:
df.isnull().sum()

App               0
Category          0
Rating            0
Reviews           0
Size              0
Installs          0
Type              0
Price             0
Content Rating    0
Genres            0
Last Updated      0
Current Ver       0
Android Ver       0
dtype: int64

In [6]:
df

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.100000,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.900000,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.700000,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.500000,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.300000,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10836,Sya9a Maroc - FR,FAMILY,4.500000,38,53M,"5,000+",Free,0,Everyone,Education,"July 25, 2017",1.48,4.1 and up
10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.000000,4,3.6M,100+,Free,0,Everyone,Education,"July 6, 2018",1.0,4.1 and up
10838,Parkinson Exercices FR,MEDICAL,4.193338,3,9.5M,"1,000+",Free,0,Everyone,Medical,"January 20, 2017",1.0,2.2 and up
10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.500000,114,Varies with device,"1,000+",Free,0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device
10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.500000,398307,19M,"10,000,000+",Free,0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device

### Q1. How many free apps are there in ART_AND_DESIGN

In [7]:
df = df.values

In [8]:
df[0]

array(['Photo Editor & Candy Camera & Grid & ScrapBook', 'ART_AND_DESIGN',
       4.1, '159', '19M', '10,000+', 'Free', '0', 'Everyone',
       'Art & Design', 'January 7, 2018', '1.0.0', '4.0.3 and up'],
      dtype=object)

gives us an array of first row in all columns

In [9]:
df[3]

array(['Sketch - Draw & Paint', 'ART_AND_DESIGN', 4.5, '215644', '25M',
       '50,000,000+', 'Free', '0', 'Teen', 'Art & Design', 'June 8, 2018',
       'Varies with device', '4.2 and up'], dtype=object)

In [10]:
for i in df:
    print(i)
    break #break function helps us to stop after one row itself and not print all rows

['Photo Editor & Candy Camera & Grid & ScrapBook' 'ART_AND_DESIGN' 4.1
 '159' '19M' '10,000+' 'Free' '0' 'Everyone' 'Art & Design'
 'January 7, 2018' '1.0.0' '4.0.3 and up']

In [11]:
for i in df:
    print(i[1],i[6])
    break

#prints only the first value entered in both second and seventh column since break is used

ART_AND_DESIGN Free

prints the second column as indexed by i and alongside the 7th which is both required by the question

In [12]:
# HOW MANY APPS for free(WITHOUT BREAK)

c = 0
for i in df:
    if(i[1]=='ART_AND_DESIGN' and i[6]=='Free'):
        c+=1

print("There are",c,"free apps from ART_AND_DESIGN")

There are 61 free apps from ART_AND_DESIGN

In [13]:
# HOW MANY APPS for paid(WITHOUT BREAK)

c = 0
for i in df:
    if(i[1]=='ART_AND_DESIGN' and i[6]=='Paid'):
        c+=1

print("There are",c,"paid apps from ART_AND_DESIGN")

There are 3 paid apps from ART_AND_DESIGN

### How many apps are there in ART_AND_DESIGN with rating more than 4.5?

In [14]:
c = 0
for i in df:
    if(i[1] == 'ART_AND_DESIGN' and i[2] > 4.5):
        c+=1
print("There are",c,"ART_AND_DESIGN apps with rating above 4.5")

There are 22 ART_AND_DESIGN apps with rating above 4.5

### How many apps are there in FAMILY with rating more than 4.5 AND free?

In [15]:
c = 0
for i in df:
    if(i[1] == 'FAMILY' and i[2] > 4.5 and i[6]=='Free'):
        c+=1
print("There are",c," free FAMILY apps with rating above 4.5")

There are 314  free FAMILY apps with rating above 4.5

### List All the free apps with rating more than 4.5 and category is FAMILY

In [16]:
print("-"*100)
print("       These are the free apps with rating more than 4.5 in category FAMILY ")
print("-"*100)
for i in df:
    if(i[1] == 'FAMILY' and i[2] > 4.5 and i[6]=='Free'):
        print(i) #print all names
print("-"*100)

----------------------------------------------------------------------------------------------------
       These are the free apps with rating more than 4.5 in category FAMILY
----------------------------------------------------------------------------------------------------
['Super ABC! Learning games for kids! Preschool apps' 'FAMILY' 4.6 '20267'
 '46M' '1,000,000+' 'Free' '0' 'Everyone' 'Educational;Education'
 'July 16, 2018' '1.1.6.7' '4.1 and up']
['Candy Pop Story' 'FAMILY' 4.7 '12948' '23M' '1,000,000+' 'Free' '0'
 'Everyone' 'Casual;Brain Games' 'May 24, 2018' '2.0.3165' '2.3 and up']
['Dog Run - Pet Dog Simulator' 'FAMILY' 4.7 '48615' '24M' '10,000,000+'
 'Free' '0' 'Everyone' 'Simulation;Action & Adventure' 'May 22, 2018'
 '1.4.12' '4.1 and up']
['Puzzle Kids - Animals Shapes and Jigsaw Puzzles' 'FAMILY' 4.6 '1109'
 '52M' '1,000,000+' 'Free' '0' 'Everyone' 'Educational;Brain Games'
 'July 18, 2018' '1.0.6' '4.1 and up']
['No. Color - Color by Number, Number Coloring' 'FAMILY' 4.8 '269194'
 '6.9M' '10,000,000+' 'Free' '0' 'Everyone' 'Entertainment;Brain Games'
 'August 3, 2018' 'Varies with device' 'Varies with device']
['Garden Fruit Legend' 'FAMILY' 4.6 '4289' '33M' '500,000+' 'Free' '0'
 'Everyone' 'Casual;Brain Games' 'July 31, 2018' '3.5.3183' '4.0.3 and up']
['Piano Kids - Music & Songs' 'FAMILY' 4.6 '46741' '50M' '10,000,000+'
 'Free' '0' 'Everyone' 'Music;Music & Video' 'August 3, 2018' '1.73'
 '4.0.3 and up']
['Duolingo: Learn Languages Free' 'FAMILY' 4.7 '6294400'
 'Varies with device' '100,000,000+' 'Free' '0' 'Everyone'
 'Education;Education' 'August 1, 2018' 'Varies with device'
 'Varies with device']
['Super ABC! Learning games for kids! Preschool apps' 'FAMILY' 4.6 '20267'
 '46M' '1,000,000+' 'Free' '0' 'Everyone' 'Educational;Education'
 'July 16, 2018' '1.1.6.7' '4.1 and up']
['Drawing for Kids Learning Games for Toddlers age 3' 'FAMILY' 4.6 '29436'
 '43M' '1,000,000+' 'Free' '0' 'Everyone' 'Educational;Education'
 'March 21, 2018' '2.0.5.0' '4.1 and up']
['Baby ABC in box! Kids alphabet games for toddlers!' 'FAMILY' 4.6 '9652'
 '53M' '1,000,000+' 'Free' '0' 'Everyone' 'Educational;Education'
 'July 16, 2018' '2.0.7.4' '4.1 and up']
['Henry Danger Crime Warp' 'FAMILY' 4.6 '9626' '28M' '1,000,000+' 'Free'
 '0' 'Everyone' 'Action;Action & Adventure' 'February 7, 2018' '1.1'
 '4.4 and up']
['Fruit Cube Blast' 'FAMILY' 4.6 '9199' '80M' '500,000+' 'Free' '0'
 'Everyone' 'Puzzle;Brain Games' 'August 3, 2018' '1.2.7' '4.1 and up']
['Toddler Kids Puzzles PUZZINGO' 'FAMILY' 4.6 '14014' '60M' '1,000,000+'
 'Free' '0' 'Everyone' 'Education;Education' 'July 6, 2018' '7.32'
 '4.0.3 and up']
['Fuzzy Seasons: Animal Forest' 'FAMILY' 4.8 '12137' '63M' '100,000+'
 'Free' '0' 'Everyone 10+' 'Simulation;Pretend Play' 'August 6, 2018'
 '149' '4.1 and up']
['Dog Run - Pet Dog Simulator' 'FAMILY' 4.7 '48701' '24M' '10,000,000+'
 'Free' '0' 'Everyone' 'Simulation;Action & Adventure' 'May 22, 2018'
 '1.4.12' '4.1 and up']
['My Oasis - Calming and Relaxing Idle Clicker Game' 'FAMILY' 4.6 '106750'
 '94M' '1,000,000+' 'Free' '0' 'Everyone' 'Simulation;Action & Adventure'
 'June 29, 2018' '1.221' '4.1 and up']
['Ninja Dash - Ronin Jump RPG' 'FAMILY' 4.7 '8508' '54M' '500,000+' 'Free'
 '0' 'Everyone 10+' 'Arcade;Action & Adventure' 'August 2, 2018' '1.1.23'
 '4.0.3 and up']
['Monster High™ Minis Mania' 'FAMILY' 4.6 '19170' '70M' '1,000,000+'
 'Free' '0' 'Everyone' 'Strategy;Action & Adventure' 'March 15, 2017'
 '1.4.2' '4.0.3 and up']
['Monica Toy TV' 'FAMILY' 4.7 '6188' '49M' '500,000+' 'Free' '0'
 'Everyone 10+' 'Entertainment;Music & Video' 'April 3, 2018' '1.6.4'
 '4.1 and up']
['Sworkit Kids - Fitness Meets Fun' 'FAMILY' 4.7 '9856' '55M' '100,000+'
 'Free' '0' 'Everyone' 'Health & Fitness;Education' 'February 2, 2016'
 '1.1.1' '4.0 and up']
['Crazy Colors: Bubbles Matching' 'FAMILY' 4.6 '3063' '1.6M' '100,000+'
 'Free' '0' 'Everyone' 'Board;Brain Games' 'May 24, 2018' '2.9.7'
 '3.0 and up']
['Pino chess' 'FAMILY' 4.8 '61' '25M' '1,000+' 'Free' '0' 'Everyone'
 'Casual;Brain Games' 'January 26, 2017' '0.1.0' '4.0 and up']
['Duolingo: Learn Languages Free' 'FAMILY' 4.7 '6294397'
 'Varies with device' '100,000,000+' 'Free' '0' 'Everyone'
 'Education;Education' 'August 1, 2018' 'Varies with device'
 'Varies with device']
['Animal Jam - Play Wild!' 'FAMILY' 4.6 '361970' '58M' '5,000,000+' 'Free'
 '0' 'Everyone' 'Casual;Pretend Play' 'August 2, 2018' '28.0.14'
 '4.1 and up']
['Dog Sim Online: Raise a Family' 'FAMILY' 4.6 '94989' '74M' '5,000,000+'
 'Free' '0' 'Teen' 'Simulation' 'April 22, 2018' '8.6' '4.0 and up']
['Color by Number - Draw Sandbox Pixel Art' 'FAMILY' 4.6 '10247' '15M'
 '1,000,000+' 'Free' '0' 'Everyone' 'Entertainment' 'July 27, 2018'
 '1.3.13' '4.1 and up']
['Build a Bridge!' 'FAMILY' 4.6 '263454' '74M' '10,000,000+' 'Free' '0'
 'Everyone' 'Puzzle' 'August 2, 2018' '2.1.1' '4.1 and up']
['Find a Way: Addictive Puzzle' 'FAMILY' 4.8 '39480' '14M' '500,000+'
 'Free' '0' 'Everyone' 'Puzzle' 'June 16, 2017' '4.1.1' '4.1 and up']
['CompTIA Exam Training' 'FAMILY' 4.8 '3053' '17M' '50,000+' 'Free' '0'
 'Everyone' 'Education' 'July 3, 2018' '1.7' '4.2 and up']
['Gymnastics Superstar - Spin your way to gold!' 'FAMILY' 4.6 '305765'
 '34M' '10,000,000+' 'Free' '0' 'Everyone' 'Role Playing' 'July 31, 2018'
 '1.1.7' '4.1 and up']
['Hungry Hearts Diner: A Tale of Star-Crossed Souls' 'FAMILY' 4.9 '46253'
 '56M' '500,000+' 'Free' '0' 'Everyone 10+' 'Simulation'
 'February 7, 2018' '1.0.1' '4.0 and up']
['Dragon Sim Online: Be A Dragon' 'FAMILY' 4.6 '111741' '66M' '5,000,000+'
 'Free' '0' 'Teen' 'Simulation' 'February 27, 2018' '5.4' '4.0 and up']
['Cat Sim Online: Play with Cats' 'FAMILY' 4.6 '137198' '81M' '5,000,000+'
 'Free' '0' 'Everyone 10+' 'Simulation' 'April 22, 2018' '3.7'
 '4.0 and up']
['Clash of Clans' 'FAMILY' 4.6 '44881447' '98M' '100,000,000+' 'Free' '0'
 'Everyone 10+' 'Strategy' 'July 15, 2018' '10.322.16' '4.1 and up']
['Clash Royale' 'FAMILY' 4.6 '23125280' '97M' '100,000,000+' 'Free' '0'
 'Everyone 10+' 'Strategy' 'June 27, 2018' '2.3.2' '4.1 and up']
['Learn C++' 'FAMILY' 4.6 '73404' '5.3M' '1,000,000+' 'Free' '0'
 'Everyone' 'Education' 'December 25, 2017' '4.5.2' '4.0 and up']
['C Programming Zone' 'FAMILY' 4.6 '1218' '4.0M' '50,000+' 'Free' '0'
 'Everyone' 'Education' 'May 13, 2017' '3.0' '4.0.3 and up']
['All C Programs' 'FAMILY' 4.7 '2387' '6.9M' '100,000+' 'Free' '0'
 'Everyone' 'Education' 'June 9, 2018' '2.5.1' '4.1 and up']
['codeEazy - C/C++/JAVA' 'FAMILY' 4.6 '130' '2.2M' '10,000+' 'Free' '0'
 'Everyone' 'Education' 'April 4, 2016' '1.0.3' '4.0.3 and up']
['C Functions' 'FAMILY' 4.8 '55' '1.5M' '1,000+' 'Free' '0' 'Everyone'
 'Education' 'September 26, 2015' '1.0' '4.0.3 and up']
['Learn Basic C - For Beginners' 'FAMILY' 4.7 '27' '772k' '5,000+' 'Free'
 '0' 'Everyone' 'Education' 'January 20, 2016' '1.0' '3.0 and up']
['C Prowess' 'FAMILY' 4.8 '306' '3.3M' '5,000+' 'Free' '0' 'Everyone'
 'Education' 'June 3, 2017' '1.2' '4.1 and up']
['101 C Programming Problems' 'FAMILY' 4.6 '498' '5.0M' '50,000+' 'Free'
 '0' 'Everyone' 'Education' 'October 15, 2017' '2.0' '4.0.3 and up']
['C BOOK-C PROGRAMS' 'FAMILY' 4.8 '138' '2.1M' '10,000+' 'Free' '0'
 'Everyone' 'Education' 'September 22, 2017' '1.0' '3.0 and up']
['Eternium' 'FAMILY' 4.8 '1506783' '89M' '10,000,000+' 'Free' '0' 'Teen'
 'Role Playing' 'July 18, 2018' '1.2.115' '4.0 and up']
['Harris J Lyrics' 'FAMILY' 4.7 '36' '7.1M' '1,000+' 'Free' '0' 'Everyone'
 'Entertainment' 'March 12, 2018' '1.3' '4.0.3 and up']
['2048 BTS J Hope KPop Puzzle Game' 'FAMILY' 4.7 '17' '2.4M' '1,000+'
 'Free' '0' 'Everyone' 'Puzzle' 'September 26, 2017' '1' '2.3.3 and up']
['J. Cole Albums (2007-2017)' 'FAMILY' 4.6 '7' '7.3M' '1,000+' 'Free' '0'
 'Mature 17+' 'Entertainment' 'April 11, 2018' '1.3' '4.0.3 and up']
['K-Otic Universe' 'FAMILY' 4.9 '55' '40M' '1,000+' 'Free' '0' 'Everyone'
 'Puzzle' 'August 3, 2018' '108' '4.1 and up']
['CASE K-12 Math English Science' 'FAMILY' 4.6 '60' '2.1M' '10,000+'
 'Free' '0' 'Everyone' 'Education' 'May 1, 2016' '1.0' '2.2 and up']
['K-Spapp, the K-Space app' 'FAMILY' 4.8 '39' '3.6M' '1,000+' 'Free' '0'
 'Everyone' 'Education' 'February 9, 2017' '1.53' '4.0.3 and up']
['EXO-L' 'FAMILY' 4.6 '67410' '865k' '1,000,000+' 'Free' '0' 'Everyone'
 'Entertainment' 'November 2, 2017' '1.0.9' '2.2 and up']
["Fantastic Chefs: Match 'n Cook" 'FAMILY' 4.7 '8600' '91M' '500,000+'
 'Free' '0' 'Everyone' 'Puzzle' 'July 27, 2018' '1.0.7' '4.0.3 and up']
['Twitch: Livestream Multiplayer Games & Esports' 'FAMILY' 4.6 '2133047'
 'Varies with device' '50,000,000+' 'Free' '0' 'Teen' 'Entertainment'
 'July 31, 2018' 'Varies with device' 'Varies with device']
['Channel U' 'FAMILY' 4.6 '34' '14M' '1,000+' 'Free' '0' 'Everyone'
 'Entertainment' 'May 21, 2018' '1.3' '4.1 and up']
['Get Free V-bucks_fortnite Hints' 'FAMILY' 4.7 '1997' '1.8M' '5,000+'
 'Free' '0' 'Everyone' 'Entertainment' 'July 21, 2018' '1.0' '4.4 and up']
['Easy V-Bux free' 'FAMILY' 4.6 '856' '2.9M' '5,000+' 'Free' '0'
 'Everyone' 'Entertainment' 'July 17, 2018' '1.0' '2.1 and up']
['X-Wing Squadron Builder' 'FAMILY' 4.6 '5898' '50M' '100,000+' 'Free' '0'
 'Everyone' 'Entertainment' 'August 1, 2017' '3.3.8.03082017' '1.6 and up']
['JW Caleb y Sofia' 'FAMILY' 4.6 '5227' '1.9M' '500,000+' 'Free' '0'
 'Everyone' 'Education' 'November 20, 2015' '1.0' '4.0.3 and up']
["PewDiePie's Tuber Simulator" 'FAMILY' 4.8 '1499466' '96M' '10,000,000+'
 'Free' '0' 'Teen' 'Casual' 'July 24, 2018' '1.25.0' '4.1 and up']
['Z-Empire: Dead Strike' 'FAMILY' 4.6 '99' '19M' '10,000+' 'Free' '0'
 'Teen' 'Strategy' 'June 8, 2018' '1.8.7' '4.0.3 and up']
['Angry Birds Blast' 'FAMILY' 4.6 '253115' '99M' '10,000,000+' 'Free' '0'
 'Everyone' 'Puzzle' 'July 27, 2018' '1.6.4' '4.4 and up']
['Angry Birds Match' 'FAMILY' 4.7 '227401' '91M' '5,000,000+' 'Free' '0'
 'Everyone' 'Puzzle' 'July 19, 2018' '1.5.0' '5.0 and up']
['Angry Birds 2' 'FAMILY' 4.6 '3881752' '57M' '100,000,000+' 'Free' '0'
 'Everyone' 'Casual' 'July 26, 2018' '2.21.1' '4.1 and up']
['Alchemy Classic Ad Free' 'FAMILY' 4.6 '20178' '9.0M' '100,000+' 'Free'
 '0' 'Everyone' 'Puzzle' 'May 26, 2014' '1.7.3' '1.6 and up']
['Nasihat - Chalo ae Pyaara' 'FAMILY' 4.7 '557' '6.7M' '10,000+' 'Free'
 '0' 'Everyone' 'Education' 'October 9, 2015' '1.0' '2.1 and up']
['9GAG: Funny Gifs, Pics, Memes & Videos for IGTV' 'FAMILY' 4.6 '1450632'
 'Varies with device' '10,000,000+' 'Free' '0' 'Teen' 'Entertainment'
 'August 3, 2018' 'Varies with device' 'Varies with device']
['Orbita AI — Exciting mobile puzzles & riddles' 'FAMILY' 4.6 '116973'
 '31M' '1,000,000+' 'Free' '0' 'Everyone' 'Puzzle' 'March 29, 2018'
 '1.1.9.1' '4.1 and up']
['Learn Artificial Intelligence' 'FAMILY' 4.6 '27' '4.2M' '10,000+' 'Free'
 '0' 'Everyone' 'Education' 'July 14, 2018' '1.1.4' '4.1 and up']
['Animal Jam - Play Wild!' 'FAMILY' 4.6 '361734' '58M' '5,000,000+' 'Free'
 '0' 'Everyone' 'Casual;Pretend Play' 'August 2, 2018' '28.0.14'
 '4.1 and up']
['AJ Official' 'FAMILY' 4.6 '31' '7.3M' '500+' 'Free' '0' 'Everyone'
 'Education' 'May 3, 2017' '0.1' '2.3 and up']
['Little Pets Animal Guardians' 'FAMILY' 4.6 '18893' '91M' '100,000+'
 'Free' '0' 'Everyone' 'Casual;Pretend Play' 'June 9, 2018' '1.4.1'
 '4.0.3 and up']
['AJ Rafael Music Lessons' 'FAMILY' 5.0 '1' '8.2M' '10+' 'Free' '0'
 'Everyone' 'Entertainment' 'November 29, 2017' '1.2.1' '4.1 and up']
['Weapon stripping 3D' 'FAMILY' 4.6 '23971' '24M' '1,000,000+' 'Free' '0'
 'Everyone' 'Simulation' 'August 4, 2018' '39.231' '4.1 and up']
['Al jazeera TV' 'FAMILY' 4.6 '9952' '3.7M' '100,000+' 'Free' '0' 'Teen'
 'Entertainment' 'July 5, 2016' '1.0.0' '4.0.3 and up']
['Al Quran Audio (Full 30 Juz)' 'FAMILY' 4.7 '7878' '3.6M' '1,000,000+'
 'Free' '0' 'Everyone' 'Education' 'May 29, 2017' '4.0' '2.3 and up']
['Quran for All (Al-Huda Int.)' 'FAMILY' 4.8 '6696' '5.3M' '100,000+'
 'Free' '0' 'Everyone' 'Education' 'February 7, 2018' '3.1.0' '4.0 and up']
['Ayat - Al Quran' 'FAMILY' 4.7 '173394' '8.5M' '5,000,000+' 'Free' '0'
 'Everyone' 'Education' 'March 13, 2018' '2.9.1' '4.0 and up']
['Quran Juz-30 - Mahad al Zahra' 'FAMILY' 4.6 '2654' '6.7M' '100,000+'
 'Free' '0' 'Everyone' 'Education' 'November 2, 2016' '1.10.0'
 '2.2 and up']
['Al Quran MP3 - Quran Reading®' 'FAMILY' 4.7 '47463' '22M' '1,000,000+'
 'Free' '0' 'Everyone' 'Education' 'April 24, 2018' '4.4' '4.0.3 and up']
['Al-Quran Ahmad Saud Offline' 'FAMILY' 4.7 '7116' '40M' '100,000+' 'Free'
 '0' 'Everyone' 'Education' 'August 9, 2016' '1.0' '2.3.3 and up']
['Virtual lover' 'FAMILY' 4.6 '45771' '28M' '1,000,000+' 'Free' '0'
 'Mature 17+' 'Entertainment' 'June 8, 2018' '1.39' '4.1 and up']
['virtual lover 3D' 'FAMILY' 4.6 '5195' '64M' '100,000+' 'Free' '0'
 'Mature 17+' 'Entertainment' 'April 18, 2018' '1.3' '4.1 and up']
['Bubbu – My Virtual Pet' 'FAMILY' 4.7 '394842' '75M' '10,000,000+' 'Free'
 '0' 'Everyone' 'Casual;Pretend Play' 'August 4, 2018' '1.50' '4.1 and up']
['AP® Guide' 'FAMILY' 5.0 '3' '2.1M' '1,000+' 'Free' '0' 'Everyone'
 'Education' 'July 31, 2017' '1.3' '4.0.3 and up']
['AP Mobile' 'FAMILY' 4.6 '117' '13M' '10,000+' 'Free' '0' 'Everyone'
 'Education' 'November 21, 2017' '1.03' '6.0 and up']
['Study AP World History' 'FAMILY' 4.6 '513' '1.6M' '10,000+' 'Free' '0'
 'Everyone' 'Education' 'July 18, 2016' '1.1.2' '4.0.3 and up']
['AP Chemistry Prep: Practice Tests and Flashcards' 'FAMILY' 4.7 '55'
 '5.4M' '10,000+' 'Free' '0' 'Everyone' 'Education' 'July 3, 2018'
 '1.6.7.1' '4.1 and up']
['AP World History: Practice Tests and Flashcards' 'FAMILY' 4.8 '21'
 '5.4M' '5,000+' 'Free' '0' 'Everyone' 'Education' 'July 3, 2018'
 '1.6.7.1' '4.1 and up']
['AP Biology Prep: Practice Tests, Flashcards' 'FAMILY' 4.6 '87' '5.4M'
 '10,000+' 'Free' '0' 'Everyone' 'Education' 'July 3, 2018' '1.6.7.1'
 '4.1 and up']
['AP European History: Practice Tests and Flashcards' 'FAMILY' 4.7 '7'
 '5.4M' '1,000+' 'Free' '0' 'Everyone' 'Education' 'July 3, 2018'
 '1.6.7.1' '4.1 and up']
['Adventure Quest World Mobile Quiz' 'FAMILY' 4.6 '28' '26M' '500+' 'Free'
 '0' 'Everyone' 'Puzzle' 'January 16, 2018' '3.1.6z' '4.0.3 and up']
['AQ Ria Retail' 'FAMILY' 5.0 '4' '52M' '50+' 'Free' '0' 'Everyone'
 'Education' 'April 3, 2018' '1.1' '4.1 and up']
['Accounting Quiz (AQ) Malaysia' 'FAMILY' 5.0 '25' 'Varies with device'
 '1,000+' 'Free' '0' 'Everyone' 'Education' 'January 29, 2018'
 'Varies with device' '4.0 and up']
["Wowkwis aq Ka'qaquj" 'FAMILY' 5.0 '1' '49M' '10+' 'Free' '0' 'Everyone'
 'Education;Education' 'February 16, 2018' '1.0' '4.0.3 and up']
['Questland: Turn Based RPG' 'FAMILY' 4.6 '31134' '48M' '1,000,000+'
 'Free' '0' 'Everyone 10+' 'Role Playing' 'August 2, 2018' '1.10.6'
 '4.1 and up']
['Grow Stone Online : 2d pixel RPG, MMORPG game' 'FAMILY' 4.7 '84389'
 '48M' '1,000,000+' 'Free' '0' 'Everyone' 'Role Playing' 'August 5, 2018'
 '1.375' '4.0.3 and up']
['Egg, Inc.' 'FAMILY' 4.7 '580160' '29M' '5,000,000+' 'Free' '0'
 'Everyone' 'Simulation' 'June 13, 2018' '1.7.5' '4.0.3 and up']
['Choices: Stories You Play' 'FAMILY' 4.6 '807155' '93M' '10,000,000+'
 'Free' '0' 'Teen' 'Simulation' 'July 30, 2018' '2.3.5' '4.0.3 and up']
['Aw Restaurant' 'FAMILY' 4.8 '4' '43M' '100+' 'Free' '0' 'Everyone'
 'Casual' 'February 6, 2018' '1.0' '4.0 and up']
['AW Training' 'FAMILY' 4.6 '11' '17M' '1,000+' 'Free' '0' 'Everyone'
 'Education' 'July 5, 2018' '3.3.2' '4.0.3 and up']
['Anime Expo 2018' 'FAMILY' 4.7 '54' '44M' '10,000+' 'Free' '0' 'Everyone'
 'Entertainment' 'June 8, 2018' '2.1' '5.0 and up']
['INTERACTIVE CALCULUS FOR MATHS AND PHYSICS' 'FAMILY' 4.8 '53' '4.4M'
 '1,000+' 'Free' '0' 'Everyone' 'Education' 'February 28, 2018' '1.3'
 '4.0.3 and up']
['Pinoy Kid Song Ako ay may Lobo' 'FAMILY' 4.6 '23' '17M' '10,000+' 'Free'
 '0' 'Everyone' 'Education' 'September 12, 2016' '1.0' '2.2 and up']
['Quran Khmer Offline AY' 'FAMILY' 5.0 '41' '4.0M' '1,000+' 'Free' '0'
 'Everyone' 'Education' 'December 13, 2017' '10.6' '4.2 and up']
['Permit Test AZ Arizona MVD DOT' 'FAMILY' 4.6 '227' '11M' '10,000+'
 'Free' '0' 'Everyone' 'Education' 'October 12, 2017' '2.9.0' '4.1 and up']
['Catalyst AZ' 'FAMILY' 4.8 '12' '8.4M' '500+' 'Free' '0' 'Teen'
 'Education' 'June 27, 2018' '3.8.0' '4.1 and up']
['Az Video Status' 'FAMILY' 4.8 '13' '6.0M' '100+' 'Free' '0' 'Everyone'
 'Entertainment' 'August 2, 2018' '1.0.4' '4.1 and up']
['Goody.ba' 'FAMILY' 4.7 '303' '42M' '10,000+' 'Free' '0' 'Everyone'
 'Entertainment' 'July 22, 2018' '2.0.5' '4.1 and up']
['Learn alif ba ta' 'FAMILY' 4.8 '23' '35M' '10,000+' 'Free' '0'
 'Everyone' 'Educational;Education' 'November 28, 2017' '1.0.2'
 '2.3 and up']
['Arabic Alphabet Alif Ba Ta Wooden Blocks' 'FAMILY' 4.6 '66' '17M'
 '10,000+' 'Free' '0' 'Everyone' 'Educational;Education'
 'February 25, 2018' '1.0.0' '2.3 and up']
["Let's Learn Alif Ba Ta" 'FAMILY' 4.6 '32' '60M' '10,000+' 'Free' '0'
 'Everyone' 'Education' 'November 29, 2017' '6' '4.0.3 and up']
['Sufara.ba' 'FAMILY' 4.9 '285' '25M' '10,000+' 'Free' '0' 'Everyone'
 'Education' 'January 5, 2018' '1.0.5' '4.4 and up']
['Elif Ba - Learn The Holy Quran' 'FAMILY' 4.8 '1491' '38M' '50,000+'
 'Free' '0' 'Everyone' 'Education' 'October 31, 2017' '1.3' '4.1 and up']
['Elifba Quran Learning Game' 'FAMILY' 4.7 '1424' '19M' '100,000+' 'Free'
 '0' 'Everyone' 'Educational' 'June 7, 2018' '2.2' '4.1 and up']
['Railroad Radio Vancouver BC' 'FAMILY' 5.0 '4' '1.7M' '100+' 'Free' '0'
 'Teen' 'Entertainment' 'June 28, 2015' '1' '2.2 and up']
['BD Online Passport Application' 'FAMILY' 4.6 '12' '2.4M' '5,000+' 'Free'
 '0' 'Everyone' 'Education' 'October 7, 2017' '3.0' '4.0.3 and up']
["BD Hospital's" 'FAMILY' 4.7 '12' '2.3M' '100+' 'Free' '0' 'Everyone'
 'Education' 'October 7, 2015' '1.1' '3.0 and up']
['Exam Result BD' 'FAMILY' 5.0 '2' '2.6M' '500+' 'Free' '0' 'Everyone'
 'Education' 'July 22, 2017' '1.0' '3.2 and up']
['BG Future School' 'FAMILY' 4.9 '16' '10M' '100+' 'Free' '0' 'Everyone'
 'Education' 'July 22, 2017' '1.0' '4.0.3 and up']
['Learn Bulgarian Free' 'FAMILY' 4.7 '3049' 'Varies with device' '50,000+'
 'Free' '0' 'Everyone' 'Education' 'May 4, 2018' 'Varies with device'
 'Varies with device']
['Bh Public School' 'FAMILY' 5.0 '2' '8.7M' '10+' 'Free' '0' 'Everyone'
 'Education' 'March 21, 2018' '1.2' '4.0.3 and up']
['BH Challenge - Museum of the Jewish People' 'FAMILY' 4.8 '12' '28M'
 '1,000+' 'Free' '0' 'Everyone' 'Education' 'March 26, 2018' '1.3.6'
 '4.2 and up']
['Bitmoji – Your Personal Emoji' 'FAMILY' 4.6 '2312084'
 'Varies with device' '100,000,000+' 'Free' '0' 'Teen' 'Entertainment'
 'July 25, 2018' 'Varies with device' '4.3 and up']
['Business Intelligence & Data' 'FAMILY' 4.9 '7' '3.5M' '1,000+' 'Free'
 '0' 'Everyone' 'Education' 'July 26, 2016' '1.0' '2.0 and up']
['TED' 'FAMILY' 4.6 '181961' '18M' '10,000,000+' 'Free' '0' 'Everyone 10+'
 'Education' 'July 27, 2018' '3.2.5' '4.1 and up']
['English Grammar Test' 'FAMILY' 4.6 '104676' '2.6M' '5,000,000+' 'Free'
 '0' 'Everyone' 'Education' 'July 18, 2018' '1.9.7' '4.0 and up']
['HON. B.J. ACS COLLEGE ALE' 'FAMILY' 5.0 '3' '1.8M' '100+' 'Free' '0'
 'Mature 17+' 'Education' 'December 26, 2016' '3.1' '4.3 and up']
['BK Video Status' 'FAMILY' 5.0 '13' '2.1M' '100+' 'Free' '0' 'Everyone'
 'Entertainment' 'July 7, 2018' '2.3' '4.4 and up']
['Audio Murli Glossary For BK' 'FAMILY' 4.7 '39' '20M' '1,000+' 'Free' '0'
 'Everyone' 'Education' 'January 25, 2016' '1.1' '4.0.3 and up']
["Baba Yaad Hai?(BK's)" 'FAMILY' 4.8 '160' '13M' '10,000+' 'Free' '0'
 'Everyone' 'Entertainment' 'March 5, 2017' '1.3' '2.3 and up']
['BK murli today (Mobile Murli) - Gyan' 'FAMILY' 4.8 '100' '4.5M' '5,000+'
 'Free' '0' 'Everyone' 'Education' 'August 5, 2018' '2.0' '4.4 and up']
['BK Murli Dictionary (H to E)' 'FAMILY' 4.6 '106' '3.9M' '10,000+' 'Free'
 '0' 'Everyone' 'Education' 'November 19, 2016' '1.1' '2.2 and up']
['BkEmu - BK-0010/11M emulator' 'FAMILY' 4.6 '222' '1.4M' '10,000+' 'Free'
 '0' 'Everyone' 'Entertainment' 'February 7, 2016' '0.4.0' '2.1 and up']
['Cerulean Heart' 'FAMILY' 4.6 '2683' '25M' '10,000+' 'Free' '0'

# DATA ANALYSIS USING CONDITIONS

In [21]:
df[df['Category'] == 'BOOKS_AND_REFERENCE']

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
139,Wattpad 📖 Free Books,BOOKS_AND_REFERENCE,4.6,2914724,Varies with device,"100,000,000+",Free,0,Teen,Books & Reference,"August 1, 2018",Varies with device,Varies with device
140,E-Book Read - Read Book for free,BOOKS_AND_REFERENCE,4.5,1857,4.9M,"50,000+",Free,0,Everyone,Books & Reference,"August 3, 2018",1.3.2,4.4 and up
141,Download free book with green book,BOOKS_AND_REFERENCE,4.6,4478,9.5M,"100,000+",Free,0,Everyone 10+,Books & Reference,"July 31, 2017",1.1,4.0 and up
142,Wikipedia,BOOKS_AND_REFERENCE,4.4,577550,Varies with device,"10,000,000+",Free,0,Everyone,Books & Reference,"August 2, 2018",Varies with device,Varies with device
143,Amazon Kindle,BOOKS_AND_REFERENCE,4.2,814080,Varies with device,"100,000,000+",Free,0,Teen,Books & Reference,"July 27, 2018",Varies with device,Varies with device
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10815,Golden Dictionary (FR-AR),BOOKS_AND_REFERENCE,4.2,5775,4.9M,"500,000+",Free,0,Everyone,Books & Reference,"July 19, 2018",7.0.4.6,4.2 and up
10819,Fanfic-FR,BOOKS_AND_REFERENCE,3.3,52,3.6M,"5,000+",Free,0,Teen,Books & Reference,"August 5, 2017",0.3.4,4.1 and up
10829,Bulgarian French Dictionary Fr,BOOKS_AND_REFERENCE,4.6,603,7.4M,"10,000+",Free,0,Everyone,Books & Reference,"June 19, 2016",2.96,4.1 and up
10833,Chemin (fr),BOOKS_AND_REFERENCE,4.8,44,619k,"1,000+",Free,0,Everyone,Books & Reference,"March 23, 2014",0.8,2.2 and up
10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,Varies with device,"1,000+",Free,0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device

prints all columns with category as books and reference

### Q. How many free apps are there in ART_AND_DESIGN?

In [22]:
df_pr = df[df['Category']=="ART_AND_DESIGN"]

In [23]:
df_pr # processed data giving us all columns in category which have value as ART AND DESIGN

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.100000,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.900000,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.700000,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.500000,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.300000,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
7174,Easy DIY CD Craft Ideas,ART_AND_DESIGN,4.193338,7,5.6M,"5,000+",Free,0,Everyone,Art & Design,"May 30, 2018",1.0,2.3 and up
8679,Dp for girls,ART_AND_DESIGN,4.200000,175,8.2M,"50,000+",Free,0,Everyone,Art & Design,"May 26, 2017",1.2,4.0.3 and up
8712,Name Art DP - Focus n Filter Text 2018,ART_AND_DESIGN,4.300000,132,7.7M,"10,000+",Free,0,Everyone,Art & Design,"January 4, 2018",1,4.1 and up
8871,Test Application DT 02,ART_AND_DESIGN,4.193338,0,1.2M,0+,Free,0,Everyone,Art & Design,"March 14, 2017",4.0,4.2 and up
8888,Spring flowers theme couleurs d t space,ART_AND_DESIGN,5.000000,1,2.9M,100+,Free,0,Everyone,Art & Design,"April 18, 2018",1.0.2,4.0 and up

In [30]:
df_pr[df_pr["Type"] == "Free"]

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.100000,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.900000,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.700000,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.500000,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.300000,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
7174,Easy DIY CD Craft Ideas,ART_AND_DESIGN,4.193338,7,5.6M,"5,000+",Free,0,Everyone,Art & Design,"May 30, 2018",1.0,2.3 and up
8679,Dp for girls,ART_AND_DESIGN,4.200000,175,8.2M,"50,000+",Free,0,Everyone,Art & Design,"May 26, 2017",1.2,4.0.3 and up
8712,Name Art DP - Focus n Filter Text 2018,ART_AND_DESIGN,4.300000,132,7.7M,"10,000+",Free,0,Everyone,Art & Design,"January 4, 2018",1,4.1 and up
8871,Test Application DT 02,ART_AND_DESIGN,4.193338,0,1.2M,0+,Free,0,Everyone,Art & Design,"March 14, 2017",4.0,4.2 and up
8888,Spring flowers theme couleurs d t space,ART_AND_DESIGN,5.000000,1,2.9M,100+,Free,0,Everyone,Art & Design,"April 18, 2018",1.0.2,4.0 and up

Hence second way of doing the same thing directly,condition within a condition

In [31]:
# printing length of those apps which are free in ART AND DESIGN

print(len(df_pr[df_pr["Type"]== "Free"]))

61

Hence, 61 apps are there

### Q.2 How many apps are there in ART_AND_DESIGN with rating more than 4.5?

In [32]:
df_pr = df[df["Category"] == "ART_AND_DESIGN"]
print(len(df_pr[df_pr["Rating"]>4.5]))

22

In [33]:
df_pr = df[df["Rating"]>4.5]
df_pr

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
9,Kids Paint Free - Drawing Fun,ART_AND_DESIGN,4.7,121,3.1M,"10,000+",Free,0,Everyone,Art & Design;Creativity,"July 3, 2018",2.8,4.0.3 and up
13,Mandala Coloring Book,ART_AND_DESIGN,4.6,4326,21M,"100,000+",Free,0,Everyone,Art & Design,"June 26, 2018",1.0.4,4.4 and up
16,Photo Designer - Write your name with shapes,ART_AND_DESIGN,4.7,3632,5.5M,"500,000+",Free,0,Everyone,Art & Design,"July 31, 2018",3.1,4.1 and up
19,ibis Paint X,ART_AND_DESIGN,4.6,224399,31M,"10,000,000+",Free,0,Everyone,Art & Design,"July 30, 2018",5.5.4,4.1 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10810,Fr Lupupa Sermons,BUSINESS,4.8,19,21M,100+,Free,0,Everyone,Business,"June 12, 2018",1.0,4.4 and up
10820,Fr. Daoud Lamei,FAMILY,5.0,22,8.6M,"1,000+",Free,0,Teen,Education,"June 27, 2018",3.8.0,4.1 and up
10829,Bulgarian French Dictionary Fr,BOOKS_AND_REFERENCE,4.6,603,7.4M,"10,000+",Free,0,Everyone,Books & Reference,"June 19, 2016",2.96,4.1 and up
10833,Chemin (fr),BOOKS_AND_REFERENCE,4.8,44,619k,"1,000+",Free,0,Everyone,Books & Reference,"March 23, 2014",0.8,2.2 and up
10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4,3.6M,100+,Free,0,Everyone,Education,"July 6, 2018",1.0,4.1 and up

### Q.2 How many FREE apps are there in FAMILY with rating more than 4.5?

In [34]:
df_pr = df[df["Category"]== "FAMILY"]
df_pr = df_pr[df_pr["Rating"]> 4.5]
len(df_pr[df_pr["Type"]== 'Free'])

314

In [35]:
# to get values
result = df_pr[df_pr["Type"]== "Free"].values

In [40]:
print("-"*100)
print("         These are the free apps in Family category with Rating above 4.5")
print("-"*100)
for i in result:
    print(i[0])
print("-"*100)

----------------------------------------------------------------------------------------------------
         These are the free apps in Family category with Rating above 4.5
----------------------------------------------------------------------------------------------------
Super ABC! Learning games for kids! Preschool apps
Candy Pop Story
Dog Run - Pet Dog Simulator
Puzzle Kids - Animals Shapes and Jigsaw Puzzles
No. Color - Color by Number, Number Coloring
Garden Fruit Legend
Piano Kids - Music & Songs
Duolingo: Learn Languages Free
Super ABC! Learning games for kids! Preschool apps
Drawing for Kids Learning Games for Toddlers age 3
Baby ABC in box! Kids alphabet games for toddlers!
Henry Danger Crime Warp
Fruit Cube Blast
Toddler Kids Puzzles PUZZINGO
Fuzzy Seasons: Animal Forest
Dog Run - Pet Dog Simulator
My Oasis - Calming and Relaxing Idle Clicker Game
Ninja Dash - Ronin Jump RPG
Monster High™ Minis Mania
Monica Toy TV
Sworkit Kids - Fitness Meets Fun
Crazy Colors: Bubbles Matching
Pino chess
Duolingo: Learn Languages Free
Animal Jam - Play Wild!
Dog Sim Online: Raise a Family
Color by Number - Draw Sandbox Pixel Art
Build a Bridge!
Find a Way: Addictive Puzzle
CompTIA Exam Training
Gymnastics Superstar - Spin your way to gold!
Hungry Hearts Diner: A Tale of Star-Crossed Souls
Dragon Sim Online: Be A Dragon
Cat Sim Online: Play with Cats
Clash of Clans
Clash Royale
Learn C++
C Programming Zone
All C Programs
codeEazy - C/C++/JAVA
C Functions
Learn Basic C - For Beginners
C Prowess
101 C Programming Problems
C BOOK-C PROGRAMS
Eternium
Harris J Lyrics
2048 BTS J Hope KPop Puzzle Game
J. Cole Albums (2007-2017)
K-Otic Universe
CASE K-12 Math English Science
K-Spapp, the K-Space app
EXO-L
Fantastic Chefs: Match 'n Cook
Twitch: Livestream Multiplayer Games & Esports
Channel U
Get Free V-bucks_fortnite Hints
Easy V-Bux free
X-Wing Squadron Builder
JW Caleb y Sofia
PewDiePie's Tuber Simulator
Z-Empire: Dead Strike
Angry Birds Blast
Angry Birds Match
Angry Birds 2
Alchemy Classic Ad Free
Nasihat - Chalo ae Pyaara
9GAG: Funny Gifs, Pics, Memes & Videos for IGTV
Orbita AI — Exciting mobile puzzles & riddles
Learn Artificial Intelligence
Animal Jam - Play Wild!
AJ Official
Little Pets Animal Guardians
AJ Rafael Music Lessons
Weapon stripping 3D
Al jazeera TV
Al Quran Audio (Full 30 Juz)
Quran for All (Al-Huda Int.)
Ayat - Al Quran
Quran Juz-30 - Mahad al Zahra
Al Quran MP3 - Quran Reading®
Al-Quran Ahmad Saud Offline
Virtual lover
virtual lover 3D
Bubbu – My Virtual Pet
AP® Guide
AP Mobile
Study AP World History
AP Chemistry Prep: Practice Tests and Flashcards
AP World History: Practice Tests and Flashcards
AP Biology Prep: Practice Tests, Flashcards
AP European History: Practice Tests and Flashcards
Adventure Quest World Mobile Quiz
AQ Ria Retail
Accounting Quiz (AQ) Malaysia
Wowkwis aq Ka'qaquj
Questland: Turn Based RPG
Grow Stone Online : 2d pixel RPG, MMORPG game
Egg, Inc.
Choices: Stories You Play
Aw Restaurant
AW Training
Anime Expo 2018
INTERACTIVE CALCULUS FOR MATHS AND PHYSICS
Pinoy Kid Song Ako ay may Lobo
Quran Khmer Offline AY
Permit Test AZ Arizona MVD DOT
Catalyst AZ
Az Video Status
Goody.ba
Learn alif ba ta
Arabic Alphabet Alif Ba Ta Wooden Blocks
Let's Learn Alif Ba Ta
Sufara.ba
Elif Ba - Learn The Holy Quran
Elifba Quran Learning Game
Railroad Radio Vancouver BC
BD Online Passport Application
BD Hospital's
Exam Result BD
BG Future School
Learn Bulgarian Free
Bh Public School
BH Challenge - Museum of the Jewish People
Bitmoji – Your Personal Emoji
Business Intelligence & Data
TED
English Grammar Test
HON. B.J. ACS COLLEGE ALE
BK Video Status
Audio Murli Glossary For BK
Baba Yaad Hai?(BK's)
BK murli today (Mobile Murli) - Gyan
BK Murli Dictionary (H to E)
BkEmu - BK-0010/11M emulator
Cerulean Heart
あなカレ【BL】無料ゲーム
BM SPM Practice
Township
Blood Pressure Diary
RoboPad
Br Shafi
Companion for Fortnite & Fortnite Battle Royale
Vlogger Go Viral - Tuber Game
Loved by King Bs
BS CS IT & SE
Marked by King Bs
COMSATS BOOK STORE FOR BS(CS)
Beauty Rental Shop
Sleeping Delivery
Wifi BT Scanner
BU Study
Barisal University App-BU Face
BU Students' Rep. Council
BU Calculator
BV Sridhara Maharaj
Quadratic Equation Solver with Steps and Graphs
Sandbox - Color by Number Coloring Pages
Sandbox Art-Sandbox Color by Number Coloring Pages
Color By Number - Sandbox Pixel Coloring Book
PixelDot - Color by Number Sandbox Pixel Art
PixPanda - Color by Number Pixel Art Coloring Book
Pixyfy: coloring by number coloring book
Draw Color by Number - Sandbox Pixel Art
Butterfly Pixel Art - coloring by number
Color by Number: Pixel Art
UNICORN - Color By Number & Pixel Art Coloring
FunnyPixels - Color by number Sandbox
No.Diamond – Colors by Number
Park Limousine: Realistic Limo Parking Simulator
CB News
CB Register
CD CHOICE TUBE
Yazdani Cd Center EllahAbad Official App
MCQ CE IT
Magana Jari ce Littafi Na Uku : Part 3 of 3
CF Life
All Info about Cg
CG FM
CG - Chemistry free
CG Jobs
BF CG Abstract Pictures
CI Dictionary
Sir C J New Primary School
Louis CK
Tic Tac CK
Castle Clash: Heroes of the Empire US
Cartoon Network Match Land
Super Slime Blitz - Gumball
Surely You Quest - Magiswords
We Bare Bears Match3 Repairs
Champions and Challengers - Adventure Time
CN Resident
CP Channel
Foothills CP
Cp Calculator for Evolution:GO
ClanManagerTT2
Christian Questions Podcast
CR & CoC Private Server - Clash Barbarians PRO
Ultimate Clash Royale Tracker
Servidor Privado de CR y CoC - Light Royale
Deck Shop for Clash Royale
Cr Aviation Academy
CS Interview Questions (TechQ)
DU CS Lectures - Learn to Code for Free
CS & IT Interview Questions
CA CS Network
CT Scan Generations
CT Brain Interpretation
Permit Test Connecticut CT DMV
Cy-Reader
MadLipz
DB Tools
DB for Hustle Castle
MARVEL Future Fight
DC N COMPANY ENTERTAINMENT RADIO!
Driver Permit Test Prep DC DMV Driver's License Ed
Coloring Book for Me & Mandala
Anime Love Story Games: ✨Shadowtime✨
DH-UFO
Idle Heroes
Duolingo: Learn Languages Free
PK and DK Audio App
dk
Account Class-12 Solutions (D K Goel) Vol-2
DL Hughley
DM Buddy » Learn Digital Marketing
Disciple Maker’s (DM) Lab
DN Employee
Dragon Nest M
CritDice - Dice Roller
Maher EL Mouaikly - Offline
Darkness Rises
Latest DP and Status Pro 2018
Faceoff DP Battle App
RPG Dragon Lapis
DQSalmaan - A fan made App
DS
MegaN64 (N64 Emulator)
DS-Students
DT Driving Test Theory
WPBS-DT
Du Chinese – Mandarin Lessons
DV ASSIST
DV Lottery Simulator
DV-2019 UK/British
DW Audio
German Listening
Piczle Lines DX
DX Simulation for OOO Dx Belt
DX Simulation for Kabuto Henshin Belt 2018
DX Simulation for Double Dx Henshin Belt 2018
KPS CHAUHAN DY/DX
DYPSOET
Typical EA Game
EC Calgary
EC Fairgrounds
GATE Syllabus for EC 2018 & Notifications
English Conversation Courses
Dance Magic Fashion Style Games
EI国际
TeamWard – live help for LoL
Master E.K
Ek Onkar
Pyaar Ek Dhoka
Ek Bander Ne Kholi Dukan
Toilet Ek Prem Katha Songs Lyrics in Hindi
Sanu Ek Pal Chain Song Videos - RAID Movie Songs
Ek Qissa He Quran Se (Qurani Waqiyat)
Lyrics of Ek Paheli Leela
Exiled Kingdoms RPG
Shabad Gurubani Punjabi mp3 free - Ek Onkar Satnam
El Falı
OWLIE BOO
Narcos: Cartel Wars
Hello English: Learn English
Learn Top 300 English Words
Masha and the Bear. Games for kids
Masha and The Bear Jam Day Match 3 games for kids
Masha and the Bear: Good Night!
EP Radio
Super Doctor 2 - My Newborn Baby ER Injection
Open Heart Surgery Hospital ER: Crazy Doctor Sim
YEBIS OpenGL ES 3.0 Tech Demo
Advanced calculator fx 991 es plus & 991 ms plus
Castle Clash: Epic Empire ES
School scientific calculator fx 500 es plus 500 ms
Lettre et demande d'emploi
daskal.eu
PokeType - Dex
Pink Guy - Ey B0ss
Ey Sey Storytime រឿងនិទានតាឥសី
Fallout Shelter
Story Time FD
FD VR Music Videos - MTV Pop and Rap in 360
Fire Emblem Heroes
Safe Santa Fe
POLARIS 2MFG
Puzzles Volvo FH 16 Trucks
Jigsaw Volvo FH 16 Trucks
FH School
FK Željezničar Izzy
Permit Test FL Florida DHSMV
FL Lottery Results
Scratch-Off Guide for FL Lotto
Canvas FL
Florida Wildflowers
How it Works: FN SCAR assault rifle
Ninja FN Button
Pin-fo
Fr Ignacio Outreach
Castle Clash: RPG War and Strategy FR
Fr. Daoud Lamei
Fr. Mike Schmitz Audio Teachings
----------------------------------------------------------------------------------------------------